### ISSUE TITLE
Issue : The URL couldn't be validated. Response does not match challenge, expected value

### ISSUE THREAD

**Issue by F-Makhokha** [somaraj/Facebook-ASP.NET-Webhook#2]
Hi SomaraJ, I am using your code but experiencing issues, when I try to register the callback url Im getting the following error.

The URL couldn't be validated. Response does not match challenge, expected value="39676783", received="\"39676783\""

I am thinking that this is caused by the Get request method when facebook is trying to validate the application.

Do you maybe know how I can fix this.

Thanks

**Comment by somaraj** [comment]
Make sure the endpoint is valid

Valid URL: https://yourdomain.com/api/webhooks
Invalid URL: https://yourdomain.com/api/webhooks/

The "/" at the end of the URL is invalid here and if provided you will get the similar error message while validating.

**Comment by F-Makhokha** [comment]
Hi I have made it the same and making look the same as you have it there but I have the port as well.

The following is my url, do i need to remove the port?
https://xxxxx.bbbbbb.co.za:1325/api/webhooks



The URL couldn't be validated. Response does not match challenge, expected value="432948094", received="\"432948094\""

**Comment by F-Makhokha** [comment]
I have made changes to the url and remove the port

like this https://yourdomain.com/api/webhooks

and now getting the following errors:

The URL couldn't be validated. Callback verification failed with the following errors: curl_errno = 51; curl_error = SSL: no alternative certificate subject name matches target host name 'mycertificate'; HTTP Status Code = 200; HTTP Message = Connection established

do you know what might be the problem?

**Comment by somaraj** [comment]
Seems to be an issue with the SSL certificate, have you configured the SSL certificate correctly?

**Comment by F-Makhokha** [comment]
Thanks Somaraj, the ssl certificate guys are looking at this for us I will update you as soon as im done, Thanks so much for the quick feedbacks.

**Comment by somaraj** [comment]
I have updated the **Get** method to return a valid **HttpResponseMessage** instead of returning a plain text. This could resolve some issue while validating the call back URL in Facebook subscription. 

Commit: 43370ae19b9a26c34d426e36102779913b92d50b

**Comment by F-Makhokha** [comment]
Thanks a lot it was able to verify.

I am  very sorry that I am asking too much, I am very new to facebook.

Is it posible to link existing campaign that is running to a webhoook so that I dont download the spreadsheet. I am busy figuring out how to get the email and the phone number and name to writem to a database.

**Comment by F-Makhokha** [comment]
My question basically is do I need to create an app for campaigns or how do I set the current campaigns to listen to my new webhook

**Comment by somaraj** [comment]
Webhooks receive notifications whenever there are updates to a chosen set of topics and their fields.
In this case whenever a user submit the lead form Facebook will post the data to the endpoint i.e. you will get real-time data not the history.

Once the subscription is successful completed, all active lead ad campaigns will communicate to the endpoint automatically. Hope this clarifies your query.

**Note: I will update the solution to read field values (i.e. name, email, mobile, etc) shortly.**

**Comment by F-Makhokha** [comment]
Thanks

**Comment by RahilModi** [comment]
@F-Makhokha how did you able to solve the issue i am getting error like **The URL couldn't be validated. Response does not match challenge, expected value="2020278015", received="\"2020278015\""**

**Comment by F-Makhokha** [comment]
@RahilModi I  made changes to  the Get method like this as modified by Somaraj:
-------------
   [HttpGet]
        public HttpResponseMessage Get()
        {
            var response = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(HttpContext.Current.Request.QueryString["hub.challenge"])
            };
            response.Content.Headers.ContentType = new MediaTypeHeaderValue("text/plain");
            return response;
        }
        #endregion Get Request
------

Make sure your SSL certificate is set up correctly and you have also set the site url on your app settings.

Let me know if you still get this
 I see you are getting received=""2020278015"" and I was getting this with "\" like received="\"2020278015"\"

**Comment by F-Makhokha** [comment]
@RahilModi  did you come right?

**Comment by F-Makhokha** [comment]
@RahilModi  also make sure this info somaraj indicated,


Make sure the endpoint is valid

Valid URL: https://yourdomain.com/api/webhooks
Invalid URL: https://yourdomain.com/api/webhooks/

The "/" at the end of the URL is invalid here and if provided you will get the similar error message while validating.

**Comment by F-Makhokha** [comment]
@RahilModi  did you come right?

**Comment by Baalamurgan** [comment]
Hi, I found it the hard way to solve this issue.

1. Make sure you use the correct port and "then" use `ngrok` (eg.3000). You have to run both ngrok and node simultaneously.
2. Use correct endpoint on both code and on the Callback URL
3. The response is a big json and you have to return `req.query["hub.challenge"]` as an Integer/Number.
<img width="462" alt="Screenshot 2023-04-10 at 7 47 44 PM" src="https://user-images.githubusercontent.com/52008152/230920333-4ba6831a-4afc-4f65-abed-94752f185e69.png">
