### ISSUE TITLE
name, email, mobile addition yet?

### ISSUE THREAD

**Issue by F-Makhokha** [somaraj/Facebook-ASP.NET-Webhook#3]
Hi @somaraj Somaraj, I would like to ask if you had a chance to include the fileds name, email, mobile, on the webhook?

**Comment by somaraj** [comment]
@F-Makhokha I am planning to work on this latest next week.

**Comment by F-Makhokha** [comment]
Thanks .
 I have active campaign  ads and need to get this leads names email and
phone numbers to my database.

**Comment by F-Makhokha** [comment]
@somaraj  Been trying to modify it but keep getting errors. basically what im intereested on is getting only lead name, email and phonenumber.

I created an app but I dont know how to link it to campaign, Im very sorry but i'm very new to this and it will be very interesting to see my info on my database.


Basic scenario 👍 

I have an advert / campaing advert on my Page with a form that requires name, email and phone number.

I run this campaign and see it has one lead who fill the form and I am still able to download the csv file and i see the details , an what i want my webhook to do is to get only those 3 fields and i write them to database.

I tried the following and is giving an error:


var leaddata = data.LeadData.FirstOrDefault();
                var ldta = leaddata?.FieldData.FirstOrDefault();

                var names = ldta.Name;
                var phones = ldta.LeadFormData.Phone;
                var emails = ldta.LeadFormData.Email;


                var formid = ldta.LeadFormData.Id;
                var leadId = ldta.LeadFormData.Id;
                var adGroupId = ldta.LeadFormData.Id;
                var createdTime = ldta.LeadFormData.Id;

                var pageId = ldta.LeadFormData.Id;
                var adId = ldta.LeadFormData.Id;


and I'm struggling to understand the code.

and also on the subscription page the email , phone and name are found to be separate and subscribe to them separately; Is there a way to subscribe to 3 fields from a for at ones of just subscribe to a form getting those data?.

Let me know if you want me to describe my issue further,

**Comment by somaraj** [comment]
@F-Makhokha I have committed the changes (eb9cc06cfd9175fb798132d7c0162711d8f63d01) to retrieve field values, you can give a try.

**Comment by F-Makhokha** [comment]
Thanks I will try it in 30 minutes.

**Comment by F-Makhokha** [comment]
Hi @somaraj  this could be my limited understanding of json, 
Im getting "FailuredSystem.NullReferenceException: Object reference not set to an instance of an object."

however this is how I would like my app to produce.

i want to call my function that writes to database like this, how do i get this fields
fbtoIDMDbase.DatatoIDMandWb2Lead(name.ToString(), email.ToString(), phone.ToString())

**Comment by F-Makhokha** [comment]
@somaraj  do you mind if we can have a telephone conversation?, I really need to get this up and running.

my email is fmakhokha@gmail.com

**Comment by somaraj** [comment]
@F-Makhokha Replace line **#62** with the below code and check if you are able to retrieve the values.

```
foreach (var fieldData in jsonObjFields.FieldData)
{
   var fieldName = fieldData.Name;
   var fieldValue = fieldData.Values.FirstOrDefault();
}
```

**Comment by F-Makhokha** [comment]
still cant get values

**Comment by somaraj** [comment]
Can you share the error log

**Comment by F-Makhokha** [comment]
Hi Im unable to connect to server to get logs for you but the error comes from this line 
if (change == null) return new HttpResponseMessage(HttpStatusCode.BadRequest);

and the errors is: Object reference not set to an instance of an object 

as far as i remember, Im thinking it could be the way im passing data to and reading from json, but im still learning this, 

I hope you can asssist.

Thanks

**Comment by F-Makhokha** [comment]
here is the correct log error:

FailuredSystem.NullReferenceException: Object reference not set to an instance of an object.
   at IDMFBLeadsAds.Controller.WebhooksController.<Post>d__2.MoveNext() in C:\Users\fannie\Documents\Visual Studio 2017\Projects\IDMFBLeadsAds\IDMFBLeadsAds\Controller\WebhooksController.cs:line 77
FailuredSystem.NullReferenceException: Object reference not set to an instance of an object.

**Comment by somaraj** [comment]
From the error message I can understand that you are trying to use something that is null. Is it possible for you to share the **WebhooksController.cs** files content?

**Comment by F-Makhokha** [comment]
@somaraj this is my entire file:


`
namespace IDMFBLeadsAds.Controller
{
    public class WebhooksController : ApiController
    {
        FbtoIDMDbase fbtoIDMDbase = new FbtoIDMDbase();

        #region Get Request

        [HttpGet]
        public HttpResponseMessage Get()
        {
            var response = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(HttpContext.Current.Request.QueryString["hub.challenge"])
            };
            response.Content.Headers.ContentType = new MediaTypeHeaderValue("text/plain");
            return response;
        }
        #endregion Get Request

        [HttpPost]
        public async Task<HttpResponseMessage> Post([FromBody] JsonData data)
        //public void Post([FromBody] JsonData data)
        {

            string url = "";
            bool test = true;
            string data2xml = "";
            string FirstName = "fnametest";
            string IDNumber = "123012362";
            string CellNo = "123012362";
            string Email = "email@email.com";
            string IncomeBrackets = "50000";


            string pat = (AppDomain.CurrentDomain.BaseDirectory + "\\fcdata.txt");
            //string paths = (@"C:\Users\fanniem\Documents\Liveapps\WEBapp\Facebook" + "\\fbdata.txt");
            using (FileStream aFile = new FileStream(pat, FileMode.Append, FileAccess.Write))
            using (StreamWriter sw = new StreamWriter(aFile))
            {
                sw.WriteLine(data);
                //LoggingErrorsandData.WriteErrorLog("Done building xml\n");
            }

            if (test)
            {
                url = @"url";
            }
            else
            {
                url =  @"url2";
            }

            Wb2Ld wb2Ld = new Wb2Ld();


            try
            {
                var entry = data.Entry.FirstOrDefault();
                var change = entry?.Changes.FirstOrDefault();
                if (change == null) return new HttpResponseMessage(HttpStatusCode.BadRequest);

                //Generate user access token here https://developers.facebook.com/tools/accesstoken/
                const string token = "mytoken";

                var leadUrl = $"https://graph.facebook.com/v2.10/{change.Value.LeadGenId}?access_token={token}";
                var formUrl = $"https://graph.facebook.com/v2.10/{change.Value.FormId}?access_token={token}";

                using (var httpClientLead = new HttpClient())
                {
                    var response = await httpClientLead.GetStringAsync(formUrl);
                    if (!string.IsNullOrEmpty(response))
                    {
                        var jsonObjLead = JsonConvert.DeserializeObject<LeadFormData>(response);
                        //jsonObjLead.Name contains the lead ad name

                        //If response is valid get the field data
                        using (var httpClientFields = new HttpClient())
                        {
                            var responseFields = await httpClientFields.GetStringAsync(leadUrl);
                            if (!string.IsNullOrEmpty(responseFields))
                            {
                                var jsonObjFields = JsonConvert.DeserializeObject<LeadData>(responseFields);
                                //jsonObjFields.FieldData contains the field value

                                foreach (var fieldData in jsonObjFields.FieldData)
                                {
                                    var fieldName = fieldData.Name;
                                    var fieldValue = fieldData.Values.FirstOrDefault();
                                    data2xml = wb2Ld.LeadToXml(fieldValue.ToString(), fieldValue.ToString(), fieldValue.ToString(), fieldValue.ToString(), IncomeBrackets);
                                    wb2Ld.SubmitLeadToCRM(data2xml, url);

                                    //string datas = leadId.ToString() + "|" + name.ToString() + "|" + phone.ToString() + "|" + email.ToString() + "|" +
                                    //               formid.ToString() + "|" + adGroupId.ToString() + "|" + createdTime.ToString() + "|" +  pageId.ToString() + "|" + adId.ToString();

                                    //Lead Id is used for further processing
                                    string paths = (AppDomain.CurrentDomain.BaseDirectory + "\\fbdata.txt");
                                    //string paths = (@"C:\Users\fanniem\Documents\Liveapps\WEBapp\Facebook" + "\\fbdata.txt");
                                    using (FileStream aFile = new FileStream(paths, FileMode.Append, FileAccess.Write))
                                    using (StreamWriter sw = new StreamWriter(aFile))
                                    {
                                        sw.WriteLine(fieldValue.ToString());
                                        //LoggingErrorsandData.WriteErrorLog("Done building xml\n");
                                    }
                                    fbtoIDMDbase.DatatoIDMandWb2Lead(fieldValue.ToString(), fieldValue.ToString(), fieldValue.ToString(), fieldValue.ToString(), "a", "ad", "222", "65656", "232");
                                }
                            }
                        }
                    }
                }
                return new HttpResponseMessage(HttpStatusCode.OK);
                
            }
            catch (Exception ex)
            {
                string datas = "Failured" + ex;
                //Lead Id is used for further processing
                string paths = (AppDomain.CurrentDomain.BaseDirectory + "\\fbdata.txt");
                using (FileStream aFile = new FileStream(paths, FileMode.Append, FileAccess.Write))
                using (StreamWriter sw = new StreamWriter(aFile))
                {
                    sw.WriteLine(datas);
                }
                Trace.WriteLine($"Error-->{ex.Message}");
                Trace.WriteLine($"StackTrace-->{ex.StackTrace}");
                return new HttpResponseMessage(HttpStatusCode.BadGateway);
            }
        }
    }
}


`

**Comment by somaraj** [comment]
@F-Makhokha I have tested the below code and it's working. Check if you are able to receive the data in email, if yes then try to implement your business logic for inserting into a database table.

```
[HttpPost]
public async Task<HttpResponseMessage> Post([FromBody] FormData data)
{
	var result = string.Empty;
	var subject = string.Empty;
	try
	{
		var entry = data.Entry.FirstOrDefault();
		if (entry != null)
		{
			var change = entry.Changes.FirstOrDefault();
			if (change != null)
			{                        
				const string token = "TOKEN";
				var leadUrl = $"https://graph.facebook.com/v2.10/{change.Value.LeadGenId}?access_token={token}";
				var body = new StringBuilder();

				using (var httpClient = new HttpClient())
				{
					var formUrl = $"https://graph.facebook.com/v2.10/{change.Value.FormId}?access_token={token}";
					var response = await httpClient.GetStringAsync(formUrl);
					if (!string.IsNullOrEmpty(response))
					{
						var json = JsonConvert.DeserializeObject<LeadFormData>(response);
						subject = $"New Facebook Lead - {json.Name}";
					}
				}

				using (var httpClient = new HttpClient())
				{
					var response = await httpClient.GetStringAsync(leadUrl);
					if (!string.IsNullOrEmpty(response))
					{
						var json = JsonConvert.DeserializeObject<LeadData>(response);
						foreach (var fieldData in json.FieldData)
						{
							//Modify the conditions as per the field configured in lead ad form
							if (fieldData.Name.ToLower() == "full_name")
								body.AppendLine($"Name : {fieldData.Values.FirstOrDefault()}\n");
							else if (fieldData.Name.ToLower() == "email")
								body.AppendLine($"Email : {fieldData.Values.FirstOrDefault()}\n");
							 else if (fieldData.Name.ToLower() == "phone_number")
								body.AppendLine($"Phone Number : {fieldData.Values.FirstOrDefault()}\n");
						}
					}
				}
				result = body.ToString();
			}
		}

		SendEmail(subject, result);
		return new HttpResponseMessage(HttpStatusCode.OK);
	}
	catch (Exception ex)
	{
		result = ex.Message;
		return new HttpResponseMessage(HttpStatusCode.BadGateway);
	}
}
```
**Hook your email sending logic here**

```
private void SendEmail(string subject, string body)
{
	try
	{
		//Hook you email sending logic
	}
	catch (Exception ex)
	{
		Trace.WriteLine($"Error >> {ex.Message} >> StackTrace {ex.StackTrace}");
	}
}
```

**Comment by F-Makhokha** [comment]
@somaraj  Should Formdata be Jsondata? 
or do i need to use some namespace?
public async Task<HttpResponseMessage> Post([FromBody] **FormData** data)

**Comment by somaraj** [comment]
@F-Makhokha sorry it was a paste error, you need to use **JsonData**

**Comment by F-Makhokha** [comment]
@somaraj  Thanks and do I only subscribe to "Page" leadgen only?

**Comment by somaraj** [comment]
@F-Makhokha my primary focus is on leadgen, you can play around with others as well.

**Comment by somaraj** [comment]
@F-Makhokha are you able to resolve the issue?

**Comment by Salimanparas** [comment]
Hi @somaraj , I am facing same issue

**Comment by Salimanparas** [comment]
using System;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using FacebookLeadAdsWebhooks.Model;
using Newtonsoft.Json;

namespace FacebookLeadAdsWebhooks.Controller
{
    public class WebhooksController : ApiController
    {
        #region Get Request
        [HttpGet]
        public HttpResponseMessage Get()
        {
            var response = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(HttpContext.Current.Request.QueryString["hub.challenge"])
            };
            response.Content.Headers.ContentType = new MediaTypeHeaderValue("text/plain");
            return response;
        }
        #endregion Get Request

        #region Post Request

        [HttpPost]
        public async Task<HttpResponseMessage> Post(JsonData data)
        {
            var result = string.Empty;
            var subject = string.Empty;
            try
            {
                var entry = data.Entry.FirstOrDefault();
                if (entry != null)
                {
                    var change = entry.Changes.FirstOrDefault();
                    if (change != null)
                    {
                        const string token = "***********";
                        var leadUrl = $"https://graph.facebook.com/v2.10/{change.Value.LeadGenId}?access_token={token}";
                        var body = new StringBuilder();

                        using (var httpClient = new HttpClient())
                        {
                            var formUrl = $"https://graph.facebook.com/v2.10/{change.Value.FormId}?access_token={token}";
                            var response = await httpClient.GetStringAsync(formUrl);
                            if (!string.IsNullOrEmpty(response))
                            {
                                var json = JsonConvert.DeserializeObject<LeadFormData>(response);
                                subject = $"New Facebook Lead - {json.Name}";
                            }
                        }

                        using (var httpClient = new HttpClient())
                        {
                            var response = await httpClient.GetStringAsync(leadUrl);
                            if (!string.IsNullOrEmpty(response))
                            {
                                var json = JsonConvert.DeserializeObject<LeadData>(response);
                                foreach (var fieldData in json.FieldData)
                                {
                                    //Modify the conditions as per the field configured in lead ad form
                                    if (fieldData.Name.ToLower() == "full_name")
                                        body.AppendLine($"Name : {fieldData.Values.FirstOrDefault()}\n");
                                    else if (fieldData.Name.ToLower() == "email")
                                        body.AppendLine($"Email : {fieldData.Values.FirstOrDefault()}\n");
                                    else if (fieldData.Name.ToLower() == "phone_number")
                                        body.AppendLine($"Phone Number : {fieldData.Values.FirstOrDefault()}\n");
                                }
                            }
                        }
                        result = body.ToString();
                    }
                }

               // SendEmail(subject, result);
                return new HttpResponseMessage(HttpStatusCode.OK);
            }
            catch (Exception ex)
            {
                result = ex.Message;
                return new HttpResponseMessage(HttpStatusCode.BadGateway);
            }
        }

        #endregion Post Request

        
    }
}

**Comment by Salimanparas** [comment]
![image](https://user-images.githubusercontent.com/71252433/103988210-b30e8080-51b3-11eb-8692-5acf2e6eb338.png)

This error I am getting
