### ISSUE TITLE
Any code examples, please?

### ISSUE THREAD

**Issue by sconlybonly** [somaraj/Facebook-ASP.NET-Webhook#4]
I'm new to all this Webhooks thing.  Is there any chance of some code examples of how to use it and what it can do?

For example, do I have to do everything in the webhook or can I use a separate app to do things with the results I get back in the webhook?

Thanks

**Comment by somaraj** [comment]
Repository is having the sample code and configuration document to get started. 

This is an Web API application and you can make another application to communicate to this end point or you can wire-up your own logic to do specific task when ever there is a real-time HTTP notifications of changes happen in Facebook Ad Form.
