### ISSUE TITLE
Its working

### ISSUE THREAD

**Issue by amarsalunke** [somaraj/Facebook-ASP.NET-Webhook#5]
Unable to get information

**Comment by somaraj** [comment]
can you please provide more detail on the issue.

**Comment by amarsalunke** [comment]
Hey somraj , i getting information leadgen Field Sample to my server , but i wanna to get live information data like name ,email,mobile.  i try to get information by using Lead Ads Testing Tool. can we talk phone or whatsapp (contact no:-8208213320).Please help me
