### ISSUE TITLE
Facebook live information like email,mobileno

### ISSUE THREAD

**Issue by amarsalunke** [somaraj/Facebook-ASP.NET-Webhook#6]
Hey somraj , i getting information leadgen Field Sample to my server , but i wanna to get live information data like name ,email,mobile. i try to get information by using Lead Ads Testing Tool. can we talk phone or whatsapp (contact no:-8208213320).Please help me

**Comment by amarsalunke** [comment]
i also receive message  Response status code does not indicate success: 400 (Bad Request)

**Comment by amarsalunke** [comment]
we can connect Skype also. Please waiting for reply

**Comment by somaraj** [comment]
If you are getting the sample data in your server then the connectivity between your application and FB seems to be fine so you should get live data. Live data are available only if there is any active Lead Ad.

**Comment by amarsalunke** [comment]
Thank you for your response.my live campaign still live.but still i am not
getting leads.any setting required for live facebook app.can we connect
with skype

**Comment by amarsalunke** [comment]
facebook App review compulsory for  get live Leads

**Comment by amarsalunke** [comment]
Hey somraj..still i waiting for your reply

**Comment by somaraj** [comment]
Will check this and update. 

- Are you still getting the response as **400**? 
- Do you have a valid **SSL** certificate installed?

**Comment by amarsalunke** [comment]
yes somraj. i also installed SSL Certificate.any thing required?

**Comment by somaraj** [comment]
Fine I will prioritize. 

You can join [![Gitter](https://badges.gitter.im/Facebook-ASP-NET-Webhook/fb-asp-net-webhook.svg)](https://gitter.im/Facebook-ASP-NET-Webhook/fb-asp-net-webhook?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) for further discussions.

**Comment by somaraj** [comment]
**Retrieving Leads requires app review**

You can set up your app to retrieve test leads in **[dev mode](https://developers.facebook.com/docs/apps#development-mode)**. After the setup is complete, you have to request an app review and switch the app to live mode in order to receive production leads.
For more details please refer **[FB documentation](https://developers.facebook.com/docs/marketplace/vehicles/retrieving-leads/)**
