### ISSUE TITLE
502 bad gateway 

### ISSUE THREAD

**Issue by shereenkhaledmahmoud** [somaraj/Facebook-ASP.NET-Webhook#8]
i need help i get 502 bad gateway, i have added the access token which i got from graph api in the token variable in the code also i am using ngrok after adding the url and the access token in the verify token it accepts it but when i try to test the leads ngrok gives me in the cmd " POST /api/webhooks             502 Bad Gateway" can you please tell me which step am i doing wrong , i appreciate your effort in this api  ,Thanks 

Shereen

**Comment by somaraj** [comment]
Please check if any of the solution [here](https://stackoverflow.com/questions/40598428/ngrok-errors-502-bad-gateway) helps solve the issue.
