### ISSUE TITLE
Access token about!

### ISSUE THREAD

**Issue by barisakr** [somaraj/Facebook-ASP.NET-Webhook#9]
Hello Somaraj,

First off all thank you for sharing this solution. 
I would like to ask you about how to get access token. I can verified my api url but can retrieved anything while testing the fields. There are too much token in facebook developer tool and i used your solution and didnt work for me. 
I used this token below.

![image](https://user-images.githubusercontent.com/44995275/89494945-e80b4700-d7bf-11ea-8cdc-148ba65fa8e5.png)

Thank you!

**Comment by Sindhoorhegde** [comment]
You have to generate token by providing all necessary permissions in developper.facebook.com using tools > graph api explorer or click https://developers.facebook.com/tools/explorer/
